Collections:
  - Name: FreeAnchor
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - FreeAnchor
        - ResNet
    Paper: https://arxiv.org/abs/1909.02466
    README: configs/free_anchor/README.md

Models:
  - Name: retinanet_free_anchor_r50_fpn_1x_coco
    In Collection: FreeAnchor
    Config: configs/free_anchor/retinanet_free_anchor_r50_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 4.9
      inference time (s/im): 0.05435
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.7
    Weights: http://download.openmmlab.com/mmdetection/v2.0/free_anchor/retinanet_free_anchor_r50_fpn_1x_coco/retinanet_free_anchor_r50_fpn_1x_coco_20200130-0f67375f.pth

  - Name: retinanet_free_anchor_r101_fpn_1x_coco
    In Collection: FreeAnchor
    Config: configs/free_anchor/retinanet_free_anchor_r101_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 6.8
      inference time (s/im): 0.06711
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.3
    Weights: http://download.openmmlab.com/mmdetection/v2.0/free_anchor/retinanet_free_anchor_r101_fpn_1x_coco/retinanet_free_anchor_r101_fpn_1x_coco_20200130-358324e6.pth

  - Name: retinanet_free_anchor_x101_32x4d_fpn_1x_coco
    In Collection: FreeAnchor
    Config: configs/free_anchor/retinanet_free_anchor_x101_32x4d_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 8.1
      inference time (s/im): 0.09009
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.9
    Weights: http://download.openmmlab.com/mmdetection/v2.0/free_anchor/retinanet_free_anchor_x101_32x4d_fpn_1x_coco/retinanet_free_anchor_x101_32x4d_fpn_1x_coco_20200130-d4846968.pth
