Collections:
  - Name: DeepLabV3
    Metadata:
      Training Data:
        - Cityscapes
        - Pascal Context
        - Pascal VOC 2012 + Aug
        - ADE20K

Models:

  - Name: deeplabv3_r50-d8_512x1024_40k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 389.11
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.09
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes/deeplabv3_r50-d8_512x1024_40k_cityscapes_20200605_022449-acadc2f8.pth
    Config: configs/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes.py



  - Name: deeplabv3_r101-d8_512x1024_40k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 520.83
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.12
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x1024_40k_cityscapes/deeplabv3_r101-d8_512x1024_40k_cityscapes_20200605_012241-7fd3f799.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_512x1024_40k_cityscapes.py



  - Name: deeplabv3_r50-d8_769x769_40k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 900.9
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.58
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_769x769_40k_cityscapes/deeplabv3_r50-d8_769x769_40k_cityscapes_20200606_113723-7eda553c.pth
    Config: configs/deeplabv3/deeplabv3_r50-d8_769x769_40k_cityscapes.py



  - Name: deeplabv3_r101-d8_769x769_40k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 1204.82
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.27
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_769x769_40k_cityscapes/deeplabv3_r101-d8_769x769_40k_cityscapes_20200606_113809-c64f889f.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_769x769_40k_cityscapes.py



  - Name: deeplabv3_r18-d8_512x1024_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 72.57
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.70
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r18-d8_512x1024_80k_cityscapes/deeplabv3_r18-d8_512x1024_80k_cityscapes_20201225_021506-23dffbe2.pth
    Config: configs/deeplabv3/deeplabv3_r18-d8_512x1024_80k_cityscapes.py



  - Name: deeplabv3_r50-d8_512x1024_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 389.11
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.32
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x1024_80k_cityscapes/deeplabv3_r50-d8_512x1024_80k_cityscapes_20200606_113404-b92cfdd4.pth
    Config: configs/deeplabv3/deeplabv3_r50-d8_512x1024_80k_cityscapes.py



  - Name: deeplabv3_r101-d8_512x1024_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 520.83
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 80.20
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x1024_80k_cityscapes/deeplabv3_r101-d8_512x1024_80k_cityscapes_20200606_113503-9e428899.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_512x1024_80k_cityscapes.py



  - Name: deeplabv3_r18-d8_769x769_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 180.18
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.60
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r18-d8_769x769_80k_cityscapes/deeplabv3_r18-d8_769x769_80k_cityscapes_20201225_021506-6452126a.pth
    Config: configs/deeplabv3/deeplabv3_r18-d8_769x769_80k_cityscapes.py



  - Name: deeplabv3_r50-d8_769x769_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 900.9
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.89
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_769x769_80k_cityscapes/deeplabv3_r50-d8_769x769_80k_cityscapes_20200606_221338-788d6228.pth
    Config: configs/deeplabv3/deeplabv3_r50-d8_769x769_80k_cityscapes.py



  - Name: deeplabv3_r101-d8_769x769_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 1204.82
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.67
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_769x769_80k_cityscapes/deeplabv3_r101-d8_769x769_80k_cityscapes_20200607_013353-60e95418.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_769x769_80k_cityscapes.py



  - Name: deeplabv3_r101-d16-mg124_512x1024_40k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 143.68
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.71
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d16-mg124_512x1024_40k_cityscapes/deeplabv3_r101-d16-mg124_512x1024_40k_cityscapes_20200908_005644-67b0c992.pth
    Config: configs/deeplabv3/deeplabv3_r101-d16-mg124_512x1024_40k_cityscapes.py



  - Name: deeplabv3_r101-d16-mg124_512x1024_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 143.68
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.36
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d16-mg124_512x1024_80k_cityscapes/deeplabv3_r101-d16-mg124_512x1024_80k_cityscapes_20200908_005644-57bb8425.pth
    Config: configs/deeplabv3/deeplabv3_r101-d16-mg124_512x1024_80k_cityscapes.py



  - Name: deeplabv3_r18b-d8_512x1024_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 71.79
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.26
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r18b-d8_512x1024_80k_cityscapes/deeplabv3_r18b-d8_512x1024_80k_cityscapes_20201225_094144-46040cef.pth
    Config: configs/deeplabv3/deeplabv3_r18b-d8_512x1024_80k_cityscapes.py



  - Name: deeplabv3_r50b-d8_512x1024_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 364.96
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.63
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50b-d8_512x1024_80k_cityscapes/deeplabv3_r50b-d8_512x1024_80k_cityscapes_20201225_155148-ec368954.pth
    Config: configs/deeplabv3/deeplabv3_r50b-d8_512x1024_80k_cityscapes.py



  - Name: deeplabv3_r101b-d8_512x1024_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 552.49
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 80.01
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101b-d8_512x1024_80k_cityscapes/deeplabv3_r101b-d8_512x1024_80k_cityscapes_20201226_171821-8fd49503.pth
    Config: configs/deeplabv3/deeplabv3_r101b-d8_512x1024_80k_cityscapes.py



  - Name: deeplabv3_r18b-d8_769x769_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 172.71
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.63
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r18b-d8_769x769_80k_cityscapes/deeplabv3_r18b-d8_769x769_80k_cityscapes_20201225_094144-fdc985d9.pth
    Config: configs/deeplabv3/deeplabv3_r18b-d8_769x769_80k_cityscapes.py



  - Name: deeplabv3_r50b-d8_769x769_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 862.07
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.80
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50b-d8_769x769_80k_cityscapes/deeplabv3_r50b-d8_769x769_80k_cityscapes_20201225_155404-87fb0cf4.pth
    Config: configs/deeplabv3/deeplabv3_r50b-d8_769x769_80k_cityscapes.py



  - Name: deeplabv3_r101b-d8_769x769_80k_cityscapes
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 1219.51
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.41
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101b-d8_769x769_80k_cityscapes/deeplabv3_r101b-d8_769x769_80k_cityscapes_20201226_190843-9142ee57.pth
    Config: configs/deeplabv3/deeplabv3_r101b-d8_769x769_80k_cityscapes.py



  - Name: deeplabv3_r50-d8_512x512_80k_ade20k
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 67.75
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 42.42
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x512_80k_ade20k/deeplabv3_r50-d8_512x512_80k_ade20k_20200614_185028-0bb3f844.pth
    Config: configs/deeplabv3/deeplabv3_r50-d8_512x512_80k_ade20k.py



  - Name: deeplabv3_r101-d8_512x512_80k_ade20k
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 98.62
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 44.08
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x512_80k_ade20k/deeplabv3_r101-d8_512x512_80k_ade20k_20200615_021256-d89c7fa4.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_512x512_80k_ade20k.py



  - Name: deeplabv3_r50-d8_512x512_160k_ade20k
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 67.75
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 42.66
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x512_160k_ade20k/deeplabv3_r50-d8_512x512_160k_ade20k_20200615_123227-5d0ee427.pth
    Config: configs/deeplabv3/deeplabv3_r50-d8_512x512_160k_ade20k.py



  - Name: deeplabv3_r101-d8_512x512_160k_ade20k
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 98.62
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 45.00
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x512_160k_ade20k/deeplabv3_r101-d8_512x512_160k_ade20k_20200615_105816-b1f72b3b.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_512x512_160k_ade20k.py



  - Name: deeplabv3_r50-d8_512x512_20k_voc12aug
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 72.05
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 76.17
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x512_20k_voc12aug/deeplabv3_r50-d8_512x512_20k_voc12aug_20200617_010906-596905ef.pth
    Config: configs/deeplabv3/deeplabv3_r50-d8_512x512_20k_voc12aug.py



  - Name: deeplabv3_r101-d8_512x512_20k_voc12aug
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 101.94
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 78.70
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x512_20k_voc12aug/deeplabv3_r101-d8_512x512_20k_voc12aug_20200617_010932-8d13832f.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_512x512_20k_voc12aug.py



  - Name: deeplabv3_r50-d8_512x512_40k_voc12aug
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 72.05
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 77.68
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x512_40k_voc12aug/deeplabv3_r50-d8_512x512_40k_voc12aug_20200613_161546-2ae96e7e.pth
    Config: configs/deeplabv3/deeplabv3_r50-d8_512x512_40k_voc12aug.py



  - Name: deeplabv3_r101-d8_512x512_40k_voc12aug
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 101.94
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 77.92
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x512_40k_voc12aug/deeplabv3_r101-d8_512x512_40k_voc12aug_20200613_161432-0017d784.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_512x512_40k_voc12aug.py



  - Name: deeplabv3_r101-d8_480x480_40k_pascal_context
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 141.04
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 46.55
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_480x480_40k_pascal_context/deeplabv3_r101-d8_480x480_40k_pascal_context_20200911_204118-1aa27336.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_480x480_40k_pascal_context.py



  - Name: deeplabv3_r101-d8_480x480_80k_pascal_context
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: 141.04
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 46.42
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_480x480_80k_pascal_context/deeplabv3_r101-d8_480x480_80k_pascal_context_20200911_170155-2a21fff3.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_480x480_80k_pascal_context.py



  - Name: deeplabv3_r101-d8_480x480_40k_pascal_context
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: None
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 52.61
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_480x480_40k_pascal_context_59/deeplabv3_r101-d8_480x480_40k_pascal_context_59_20210416_110332-cb08ea46.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_480x480_40k_pascal_context.py



  - Name: deeplabv3_r101-d8_480x480_80k_pascal_context_59
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im):
        - value: None
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 52.46
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_480x480_80k_pascal_context_59/deeplabv3_r101-d8_480x480_80k_pascal_context_59_20210416_113002-26303993.pth
    Config: configs/deeplabv3/deeplabv3_r101-d8_480x480_80k_pascal_context_59.py
