Collections:
  - Name: APCNet
    Metadata:
      Training Data:
        - Cityscapes
        - ADE20K

Models:

  - Name: apcnet_r50-d8_512x1024_40k_cityscapes
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 280.11
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.02
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r50-d8_512x1024_40k_cityscapes/apcnet_r50-d8_512x1024_40k_cityscapes_20201214_115717-5e88fa33.pth
    Config: configs/apcnet/apcnet_r50-d8_512x1024_40k_cityscapes.py



  - Name: apcnet_r101-d8_512x1024_40k_cityscapes
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 465.12
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.08
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r101-d8_512x1024_40k_cityscapes/apcnet_r101-d8_512x1024_40k_cityscapes_20201214_115716-abc9d111.pth
    Config: configs/apcnet/apcnet_r101-d8_512x1024_40k_cityscapes.py



  - Name: apcnet_r50-d8_769x769_40k_cityscapes
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 657.89
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.89
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r50-d8_769x769_40k_cityscapes/apcnet_r50-d8_769x769_40k_cityscapes_20201214_115717-2a2628d7.pth
    Config: configs/apcnet/apcnet_r50-d8_769x769_40k_cityscapes.py



  - Name: apcnet_r101-d8_769x769_40k_cityscapes
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 970.87
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.96
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r101-d8_769x769_40k_cityscapes/apcnet_r101-d8_769x769_40k_cityscapes_20201214_115718-b650de90.pth
    Config: configs/apcnet/apcnet_r101-d8_769x769_40k_cityscapes.py



  - Name: apcnet_r50-d8_512x1024_80k_cityscapes
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 280.11
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.96
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r50-d8_512x1024_80k_cityscapes/apcnet_r50-d8_512x1024_80k_cityscapes_20201214_115716-987f51e3.pth
    Config: configs/apcnet/apcnet_r50-d8_512x1024_80k_cityscapes.py



  - Name: apcnet_r101-d8_512x1024_80k_cityscapes
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 465.12
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.64
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r101-d8_512x1024_80k_cityscapes/apcnet_r101-d8_512x1024_80k_cityscapes_20201214_115705-b1ff208a.pth
    Config: configs/apcnet/apcnet_r101-d8_512x1024_80k_cityscapes.py



  - Name: apcnet_r50-d8_769x769_80k_cityscapes
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 657.89
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.79
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r50-d8_769x769_80k_cityscapes/apcnet_r50-d8_769x769_80k_cityscapes_20201214_115718-7ea9fa12.pth
    Config: configs/apcnet/apcnet_r50-d8_769x769_80k_cityscapes.py



  - Name: apcnet_r101-d8_769x769_80k_cityscapes
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 970.87
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.45
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r101-d8_769x769_80k_cityscapes/apcnet_r101-d8_769x769_80k_cityscapes_20201214_115716-a7fbc2ab.pth
    Config: configs/apcnet/apcnet_r101-d8_769x769_80k_cityscapes.py



  - Name: apcnet_r50-d8_512x512_80k_ade20k
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 50.99
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 42.20
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r50-d8_512x512_80k_ade20k/apcnet_r50-d8_512x512_80k_ade20k_20201214_115705-a8626293.pth
    Config: configs/apcnet/apcnet_r50-d8_512x512_80k_ade20k.py



  - Name: apcnet_r101-d8_512x512_80k_ade20k
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 76.34
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 45.54
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r101-d8_512x512_80k_ade20k/apcnet_r101-d8_512x512_80k_ade20k_20201214_115704-c656c3fb.pth
    Config: configs/apcnet/apcnet_r101-d8_512x512_80k_ade20k.py



  - Name: apcnet_r50-d8_512x512_160k_ade20k
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 50.99
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 43.40
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r50-d8_512x512_160k_ade20k/apcnet_r50-d8_512x512_160k_ade20k_20201214_115706-25fb92c2.pth
    Config: configs/apcnet/apcnet_r50-d8_512x512_160k_ade20k.py



  - Name: apcnet_r101-d8_512x512_160k_ade20k
    In Collection: APCNet
    Metadata:
      inference time (ms/im):
        - value: 76.34
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 45.41
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/apcnet/apcnet_r101-d8_512x512_160k_ade20k/apcnet_r101-d8_512x512_160k_ade20k_20201214_115705-73f9a8d7.pth
    Config: configs/apcnet/apcnet_r101-d8_512x512_160k_ade20k.py
