MODEL:
  PRETRAIN_PATH: '/root/.cache/torch/checkpoints/resnet50-19c8e357.pth'


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax'
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [30, 55]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 20
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 128

OUTPUT_DIR: "/home/haoluo/log/reid/market1501/softmax_bs64_256x128"


