Collections:
  - Name: GHM
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - GHM-C
        - GHM-R
        - FPN
        - ResNet
    Paper: https://arxiv.org/abs/1811.05181
    README: configs/ghm/README.md

Models:
  - Name: retinanet_ghm_r50_fpn_1x_coco
    In Collection: GHM
    Config: configs/ghm/retinanet_ghm_r50_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 4.0
      inference time (s/im): 0.30303
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.0
    Weights: http://download.openmmlab.com/mmdetection/v2.0/ghm/retinanet_ghm_r50_fpn_1x_coco/retinanet_ghm_r50_fpn_1x_coco_20200130-a437fda3.pth

  - Name: retinanet_ghm_r101_fpn_1x_coco
    In Collection: GHM
    Config: configs/ghm/retinanet_ghm_r101_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 6.0
      inference time (s/im): 0.22727
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 39.1
    Weights: http://download.openmmlab.com/mmdetection/v2.0/ghm/retinanet_ghm_r101_fpn_1x_coco/retinanet_ghm_r101_fpn_1x_coco_20200130-c148ee8f.pth

  - Name: retinanet_ghm_x101_32x4d_fpn_1x_coco
    In Collection: GHM
    Config: configs/ghm/retinanet_ghm_x101_32x4d_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 7.2
      inference time (s/im): 0.19608
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.7
    Weights: http://download.openmmlab.com/mmdetection/v2.0/ghm/retinanet_ghm_x101_32x4d_fpn_1x_coco/retinanet_ghm_x101_32x4d_fpn_1x_coco_20200131-e4333bd0.pth

  - Name: retinanet_ghm_x101_64x4d_fpn_1x_coco
    In Collection: GHM
    Config: configs/ghm/retinanet_ghm_x101_64x4d_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 10.3
      inference time (s/im): 0.19231
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.4
    Weights: http://download.openmmlab.com/mmdetection/v2.0/ghm/retinanet_ghm_x101_64x4d_fpn_1x_coco/retinanet_ghm_x101_64x4d_fpn_1x_coco_20200131-dd381cef.pth
