Collections:
  - Name: FP16
    Metadata:
      Training Data: COCO
      Training Techniques:
        - Mixed Precision Training
      Training Resources: 8x NVIDIA V100 GPUs
    Paper: https://arxiv.org/abs/1710.03740
    README: configs/fp16/README.md

Models:
  - Name: faster_rcnn_r50_fpn_fp16_1x_coco
    In Collection: FP16
    Config: configs/fp16/faster_rcnn_r50_fpn_fp16_1x_coco.py
    Metadata:
      Training Memory (GB): 3.4
      inference time (s/im): 0.03472
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.5
    Weights: http://download.openmmlab.com/mmdetection/v2.0/fp16/faster_rcnn_r50_fpn_fp16_1x_coco/faster_rcnn_r50_fpn_fp16_1x_coco_20200204-d4dc1471.pth

  - Name: mask_rcnn_r50_fpn_fp16_1x_coco
    In Collection: FP16
    Config: configs/fp16/mask_rcnn_r50_fpn_fp16_1x_coco.py
    Metadata:
      Training Memory (GB): 3.6
      inference time (s/im): 0.04149
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.1
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP:  34.7
    Weights: http://download.openmmlab.com/mmdetection/v2.0/fp16/mask_rcnn_r50_fpn_fp16_1x_coco/mask_rcnn_r50_fpn_fp16_1x_coco_20200205-59faf7e4.pth

  - Name: retinanet_r50_fpn_fp16_1x_coco
    In Collection: FP16
    Config: configs/fp16/retinanet_r50_fpn_fp16_1x_coco.py
    Metadata:
      Training Memory (GB): 2.8
      inference time (s/im): 0.03165
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.4
    Weights: http://download.openmmlab.com/mmdetection/v2.0/fp16/retinanet_r50_fpn_fp16_1x_coco/retinanet_r50_fpn_fp16_1x_coco_20200702-0dbfb212.pth
