# @package _group_

hydra:
  run:
    dir: ./wav2vec2.0

common:
  fp16: true
  log_format: json
  log_interval: 1

checkpoint:
  save_interval_updates: 1000
  save_interval: 50
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer
  restore_file: 'None'

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: ltr

dataset:
  num_workers: 6
  batch_size: 8
  max_tokens: 3200000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 1000
  validate_interval: 50
  validate_interval_updates: 1000
  valid_subset: valid

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 20000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ./data/wav2vec_small.pt
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0
