SOURCE: GTA
TARGET: Cityscapes
EXP_NAME: GTA2Cityscapes_AdvEnt_MinEnt
NUM_WORKERS: 4
TEST:
  MODE: single
  MODEL:
    - DeepLabv2
    - DeepLabv2
  MULTI_LEVEL:
    - True
    - True
  RESTORE_FROM:
    - ../../pretrained_models/gta2cityscapes_advent.pth
    - ../../pretrained_models/gta2cityscapes_minent_ER.pth
  MODEL_WEIGHT:
    - 0.5
    - 0.5