MODEL:
  TYPE: cross-scale
  NAME: cros_large_patch4_group7_224
  DROP_PATH_RATE: 0.5
  CROS:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    GROUP_SIZE: [ 7, 7, 7, 7 ]
    PATCH_SIZE: [4, 8, 16, 32]
    MERGE_SIZE: [[2, 4], [2,4], [2, 4]]