Collections:
  - Name: Generalized Focal Loss
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - Generalized Focal Loss
        - FPN
        - ResNet
    Paper: https://arxiv.org/abs/2006.04388
    README: configs/gfl/README.md

Models:
  - Name: gfl_r50_fpn_1x_coco
    In Collection: Generalized Focal Loss
    Config: configs/gfl/gfl_r50_fpn_1x_coco.py
    Metadata:
      inference time (s/im): 0.05128
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.2
    Weights: http://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_r50_fpn_1x_coco/gfl_r50_fpn_1x_coco_20200629_121244-25944287.pth

  - Name: gfl_r50_fpn_mstrain_2x_coco
    In Collection: Generalized Focal Loss
    Config: configs/gfl/gfl_r50_fpn_mstrain_2x_coco.py
    Metadata:
      inference time (s/im): 0.05128
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 42.9
    Weights: http://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_r50_fpn_mstrain_2x_coco/gfl_r50_fpn_mstrain_2x_coco_20200629_213802-37bb1edc.pth

  - Name: gfl_r101_fpn_mstrain_2x_coco
    In Collection: Generalized Focal Loss
    Config: configs/gfl/gfl_r101_fpn_mstrain_2x_coco.py
    Metadata:
      inference time (s/im): 0.06803
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.7
    Weights: http://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_r101_fpn_mstrain_2x_coco/gfl_r101_fpn_mstrain_2x_coco_20200629_200126-dd12f847.pth

  - Name: gfl_r101_fpn_dconv_c3-c5_mstrain_2x_coco
    In Collection: Generalized Focal Loss
    Config: configs/gfl/gfl_r101_fpn_dconv_c3-c5_mstrain_2x_coco.py
    Metadata:
      inference time (s/im): 0.07752
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 47.1
    Weights: http://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_r101_fpn_dconv_c3-c5_mstrain_2x_coco/gfl_r101_fpn_dconv_c3-c5_mstrain_2x_coco_20200630_102002-134b07df.pth

  - Name: gfl_x101_32x4d_fpn_mstrain_2x_coco
    In Collection: Generalized Focal Loss
    Config: configs/gfl/gfl_x101_32x4d_fpn_mstrain_2x_coco.py
    Metadata:
      inference time (s/im): 0.08264
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 45.9
    Weights: http://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_x101_32x4d_fpn_mstrain_2x_coco/gfl_x101_32x4d_fpn_mstrain_2x_coco_20200630_102002-50c1ffdb.pth

  - Name: gfl_x101_32x4d_fpn_dconv_c4-c5_mstrain_2x_coco
    In Collection: Generalized Focal Loss
    Config: configs/gfl/gfl_x101_32x4d_fpn_dconv_c4-c5_mstrain_2x_coco.py
    Metadata:
      inference time (s/im): 0.09346
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 48.1
    Weights: http://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_x101_32x4d_fpn_dconv_c4-c5_mstrain_2x_coco/gfl_x101_32x4d_fpn_dconv_c4-c5_mstrain_2x_coco_20200630_102002-14a2bf25.pth
