Collections:
  - Name: SCNet
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - FPN
        - ResNet
        - SCNet
    Paper: https://arxiv.org/abs/2012.10150
    README: configs/scnet/README.md

Models:
  - Name: scnet_r50_fpn_1x_coco
    In Collection: SCNet
    Config: configs/scnet/scnet_r50_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 7.0
      inference time (s/im): 0.16129
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 43.5
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 39.2
    Weights: https://drive.google.com/file/d/1K5_8-P0EC43WZFtoO3q9_JE-df8pEc7J/view?usp=sharing

  - Name: scnet_r50_fpn_20e_coco
    In Collection: SCNet
    Config: configs/scnet/scnet_r50_fpn_20e_coco.py
    Metadata:
      Training Memory (GB): 7.0
      inference time (s/im): 0.16129
      Epochs: 20
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.5
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 40.0
    Weights: https://drive.google.com/file/d/15VGLCt5-IO5TbzB4Kw6ZyoF6QH0Q511A/view?usp=sharing

  - Name: scnet_r101_fpn_20e_coco
    In Collection: SCNet
    Config: configs/scnet/scnet_r101_fpn_20e_coco.py
    Metadata:
      Training Memory (GB): 8.9
      inference time (s/im): 0.17241
      Epochs: 20
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 45.8
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 40.9
    Weights: https://drive.google.com/file/d/1aeCGHsOBdfIqVBnBPp0JUE_RSIau3583/view?usp=sharing

  - Name: scnet_x101_64x4d_fpn_20e_coco
    In Collection: SCNet
    Config: configs/scnet/scnet_x101_64x4d_fpn_20e_coco.py
    Metadata:
      Training Memory (GB): 13.2
      inference time (s/im): 0.20408
      Epochs: 20
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 47.5
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 42.3
    Weights: https://drive.google.com/file/d/1YjgutUKz4TTPpqSWGKUTkZJ8_X-kyCfY/view?usp=sharing
