_BASE_: "../Base-RCNN-FPN.yaml"
INPUT:
  FIX_SHAPE: (1344, 1344)
MODEL:
  WEIGHTS: "./R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: CascadeROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
