 python scripts/txt2img.py \
        --prompt "a professional photograph of an astronaut riding a horse" \
        --ckpt /xxx/stable_diffusion_v2-1_ckpt/v2-1_768-ema-pruned.ckpt \
        --config configs/stable-diffusion/v2-inference-v.yaml \
        --H 768 \
        --W 768 \
        --device cuda \
        --device_id 4 \
        --precision full \
        --n_samples 1
        --n_iter 1
        --dpm
        --steps 15
