_BASE_: "Base-CenterMask-Lite-VoVNet.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/rptgw6stppbiw1u/vovnet19_ese_detectron2.pth?dl=1"
  VOVNET:
    CONV_BODY : "V-19-eSE"
SOLVER:
  STEPS: (300000, 340000)
  MAX_ITER: 360000
OUTPUT_DIR: "output/centermask/CenterMask-Lite-V-19-ms-4x"
