_BASE_: "Base-Panoptic-VoVNet-FPN.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/8xl0cb3jj51f45a/vovnet57_ese_detectron2.pth?dl=1"
  VOVNET:
    CONV_BODY : "V-57-eSE"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/Panoptic-CenterMask-V-57-eSE-FPN-ms-3x"