criterions:
  PerformanceLoss:
    def_file: ./loss/PriorCELoss.py
    loss_params: {num_classes: 8142, prior_txt: './data/iNaturalist18/iNaturalist18_train.txt'}
    optim_params: null
    weight: 1.0
last: false
model_dir: null
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0001}
    scheduler_params: {coslr: false, warmup: false, step_size: 30, gamma: 0.1}
    params: {dataset: iNaturalist18, feat_dim: 2048, num_classes: 8142, stage1_weights: false}
  feat_model:
    def_file: ./models/ResNet50Feature.py
    fix: false
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0001}
    scheduler_params: {coslr: false, warmup: false, step_size: 30, gamma: 0.1}
    params: {dataset: iNaturalist18, dropout: null, stage1_weights: false, use_fc: false}
shuffle: false
training_opt:
  backbone: resnet50
  batch_size: 256
  dataset: iNaturalist18
  display_step: 10
  display_grad: False
  display_grad_step: 10
  feature_dim: 2048
  log_dir: ./exp_results/test
  work_dir: ./exp_results
  exp_name: test
  num_classes: 8142
  num_epochs: 200
  num_workers: 12
  open_threshold: 0.1
  sampler: null
  sub_dir: models
