assign:
  issues: enabled
  pull_requests: disabled
  strategy:
    # random
    daily-shift-based
  scedule:
    '*/1 * * * *'
  assignees:
    - ly015
    - Tau-J
    - Ben-Louis
    - Tau-J
    - Ben-Louis
    - ly015
    - ly015
