Collections:
  - Name: FPN
    Metadata:
      Training Data:
        - Cityscapes
        - Pascal VOC 2012 + Aug
        - ADE20K

Models:

  - Name: fpn_r50_512x1024_80k_cityscapes
    In Collection: FPN
    Metadata:
      inference time (ms/im):
        - value: 73.86
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 74.52
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/sem_fpn/fpn_r50_512x1024_80k_cityscapes/fpn_r50_512x1024_80k_cityscapes_20200717_021437-94018a0d.pth
    Config: configs/fpn/fpn_r50_512x1024_80k_cityscapes.py



  - Name: fpn_r101_512x1024_80k_cityscapes
    In Collection: FPN
    Metadata:
      inference time (ms/im):
        - value: 97.18
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.80
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/sem_fpn/fpn_r101_512x1024_80k_cityscapes/fpn_r101_512x1024_80k_cityscapes_20200717_012416-c5800d4c.pth
    Config: configs/fpn/fpn_r101_512x1024_80k_cityscapes.py



  - Name: fpn_r50_512x512_160k_ade20k
    In Collection: FPN
    Metadata:
      inference time (ms/im):
        - value: 17.93
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 37.49
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/sem_fpn/fpn_r50_512x512_160k_ade20k/fpn_r50_512x512_160k_ade20k_20200718_131734-5b5a6ab9.pth
    Config: configs/fpn/fpn_r50_512x512_160k_ade20k.py



  - Name: fpn_r101_512x512_160k_ade20k
    In Collection: FPN
    Metadata:
      inference time (ms/im):
        - value: 24.64
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 39.35
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/sem_fpn/fpn_r101_512x512_160k_ade20k/fpn_r101_512x512_160k_ade20k_20200718_131734-306b5004.pth
    Config: configs/fpn/fpn_r101_512x512_160k_ade20k.py
