Collections:
  - Name: PSANet
    Metadata:
      Training Data:
        - Cityscapes
        - Pascal VOC 2012 + Aug
        - ADE20K

Models:

  - Name: psanet_r50-d8_512x1024_40k_cityscapes
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 315.46
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.63
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x1024_40k_cityscapes/psanet_r50-d8_512x1024_40k_cityscapes_20200606_103117-99fac37c.pth
    Config: configs/psanet/psanet_r50-d8_512x1024_40k_cityscapes.py



  - Name: psanet_r101-d8_512x1024_40k_cityscapes
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 454.55
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.14
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x1024_40k_cityscapes/psanet_r101-d8_512x1024_40k_cityscapes_20200606_001418-27b9cfa7.pth
    Config: configs/psanet/psanet_r101-d8_512x1024_40k_cityscapes.py



  - Name: psanet_r50-d8_769x769_40k_cityscapes
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 714.29
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.99
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_769x769_40k_cityscapes/psanet_r50-d8_769x769_40k_cityscapes_20200530_033717-d5365506.pth
    Config: configs/psanet/psanet_r50-d8_769x769_40k_cityscapes.py



  - Name: psanet_r101-d8_769x769_40k_cityscapes
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 1020.41
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.43
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_769x769_40k_cityscapes/psanet_r101-d8_769x769_40k_cityscapes_20200530_035107-997da1e6.pth
    Config: configs/psanet/psanet_r101-d8_769x769_40k_cityscapes.py



  - Name: psanet_r50-d8_512x1024_80k_cityscapes
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 315.46
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.24
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x1024_80k_cityscapes/psanet_r50-d8_512x1024_80k_cityscapes_20200606_161842-ab60a24f.pth
    Config: configs/psanet/psanet_r50-d8_512x1024_80k_cityscapes.py



  - Name: psanet_r101-d8_512x1024_80k_cityscapes
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 454.55
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.31
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x1024_80k_cityscapes/psanet_r101-d8_512x1024_80k_cityscapes_20200606_161823-0f73a169.pth
    Config: configs/psanet/psanet_r101-d8_512x1024_80k_cityscapes.py



  - Name: psanet_r50-d8_769x769_80k_cityscapes
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 714.29
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.31
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_769x769_80k_cityscapes/psanet_r50-d8_769x769_80k_cityscapes_20200606_225134-fe42f49e.pth
    Config: configs/psanet/psanet_r50-d8_769x769_80k_cityscapes.py



  - Name: psanet_r101-d8_769x769_80k_cityscapes
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 1020.41
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.69
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_769x769_80k_cityscapes/psanet_r101-d8_769x769_80k_cityscapes_20200606_214550-7665827b.pth
    Config: configs/psanet/psanet_r101-d8_769x769_80k_cityscapes.py



  - Name: psanet_r50-d8_512x512_80k_ade20k
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 52.88
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 41.14
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x512_80k_ade20k/psanet_r50-d8_512x512_80k_ade20k_20200614_144141-835e4b97.pth
    Config: configs/psanet/psanet_r50-d8_512x512_80k_ade20k.py



  - Name: psanet_r101-d8_512x512_80k_ade20k
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 76.16
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 43.80
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x512_80k_ade20k/psanet_r101-d8_512x512_80k_ade20k_20200614_185117-1fab60d4.pth
    Config: configs/psanet/psanet_r101-d8_512x512_80k_ade20k.py



  - Name: psanet_r50-d8_512x512_160k_ade20k
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 52.88
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 41.67
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x512_160k_ade20k/psanet_r50-d8_512x512_160k_ade20k_20200615_161258-148077dd.pth
    Config: configs/psanet/psanet_r50-d8_512x512_160k_ade20k.py



  - Name: psanet_r101-d8_512x512_160k_ade20k
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 76.16
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 43.74
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x512_160k_ade20k/psanet_r101-d8_512x512_160k_ade20k_20200615_161537-dbfa564c.pth
    Config: configs/psanet/psanet_r101-d8_512x512_160k_ade20k.py



  - Name: psanet_r50-d8_512x512_20k_voc12aug
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 54.82
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 76.39
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x512_20k_voc12aug/psanet_r50-d8_512x512_20k_voc12aug_20200617_102413-2f1bbaa1.pth
    Config: configs/psanet/psanet_r50-d8_512x512_20k_voc12aug.py



  - Name: psanet_r101-d8_512x512_20k_voc12aug
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 79.18
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 77.91
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x512_20k_voc12aug/psanet_r101-d8_512x512_20k_voc12aug_20200617_110624-946fef11.pth
    Config: configs/psanet/psanet_r101-d8_512x512_20k_voc12aug.py



  - Name: psanet_r50-d8_512x512_40k_voc12aug
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 54.82
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 76.30
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x512_40k_voc12aug/psanet_r50-d8_512x512_40k_voc12aug_20200613_161946-f596afb5.pth
    Config: configs/psanet/psanet_r50-d8_512x512_40k_voc12aug.py



  - Name: psanet_r101-d8_512x512_40k_voc12aug
    In Collection: PSANet
    Metadata:
      inference time (ms/im):
        - value: 79.18
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 77.73
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x512_40k_voc12aug/psanet_r101-d8_512x512_40k_voc12aug_20200613_161946-1f560f9e.pth
    Config: configs/psanet/psanet_r101-d8_512x512_40k_voc12aug.py
