Collections:
  - Name: RepPoints
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - Group Normalization
        - FPN
        - RepPoints
        - ResNet
    Paper: https://arxiv.org/abs/1904.11490
    README: configs/reppoints/README.md

Models:
  - Name: bbox_r50_grid_fpn_gn-neck+head_1x_coco
    In Collection: RepPoints
    Config: configs/reppoints/bbox_r50_grid_fpn_gn-neck+head_1x_coco.py
    Metadata:
      Training Memory (GB): 3.9
      inference time (s/im): 0.06289
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.4
    Weights: http://download.openmmlab.com/mmdetection/v2.0/reppoints/bbox_r50_grid_fpn_gn-neck%2Bhead_1x_coco/bbox_r50_grid_fpn_gn-neck%2Bhead_1x_coco_20200329-c98bfa96.pth

  - Name: bbox_r50_grid_center_fpn_gn-neck+Bhead_1x_coco
    In Collection: RepPoints
    Config: configs/reppoints/bbox_r50_grid_center_fpn_gn-neck+Bhead_1x_coco.py
    Metadata:
      Training Memory (GB): 3.9
      inference time (s/im): 0.06494
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.4
    Weights: http://download.openmmlab.com/mmdetection/v2.0/reppoints/bbox_r50_grid_center_fpn_gn-neck%2Bhead_1x_coco/bbox_r50_grid_center_fpn_gn-neck%2Bhead_1x_coco_20200330-00f73d58.pth

  - Name: reppoints_moment_r50_fpn_1x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints_moment_r50_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 3.3
      inference time (s/im): 0.05405
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.0
    Weights: http://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r50_fpn_1x_coco/reppoints_moment_r50_fpn_1x_coco_20200330-b73db8d1.pth

  - Name: reppoints_moment_r50_fpn_gn-neck%2Bhead_1x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints_moment_r50_fpn_gn-neck%2Bhead_1x_coco.py
    Metadata:
      Training Memory (GB): 3.9
      inference time (s/im): 0.05714
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.1
    Weights: http://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r50_fpn_gn-neck%2Bhead_1x_coco/reppoints_moment_r50_fpn_gn-neck%2Bhead_1x_coco_20200329-4b38409a.pth

  - Name: reppoints_moment_r50_fpn_gn-neck+head_2x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints_moment_r50_fpn_gn-neck+head_2x_coco.py
    Metadata:
      Training Memory (GB): 3.9
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.6
    Weights: http://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r50_fpn_gn-neck%2Bhead_2x_coco/reppoints_moment_r50_fpn_gn-neck%2Bhead_2x_coco_20200329-91babaa2.pth

  - Name: reppoints_moment_r101_fpn_gn-neck+head_2x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints_moment_r101_fpn_gn-neck+head_2x_coco.py
    Metadata:
      Training Memory (GB): 5.8
      inference time (s/im): 0.07299
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.5
    Weights: http://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r101_fpn_gn-neck%2Bhead_2x_coco/reppoints_moment_r101_fpn_gn-neck%2Bhead_2x_coco_20200329-4fbc7310.pth

  - Name: reppoints_moment_r101_fpn_dconv_c3-c5_gn-neck+head_2x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints_moment_r101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py
    Metadata:
      Training Memory (GB): 5.9
      inference time (s/im): 0.08264
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 42.9
    Weights: http://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r101_fpn_dconv_c3-c5_gn-neck%2Bhead_2x_coco/reppoints_moment_r101_fpn_dconv_c3-c5_gn-neck%2Bhead_2x_coco_20200329-3309fbf2.pth

  - Name: reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py
    Metadata:
      Training Memory (GB): 7.1
      inference time (s/im): 0.10753
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.2
    Weights: http://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck%2Bhead_2x_coco/reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck%2Bhead_2x_coco_20200329-f87da1ea.pth
