model:
  type: wresnet28_2
dataset: cifar10
aug: fa_reduced_cifar10   # autoaug_extend
cutout: 16

# UDA-related hyperparams
batch: 32
batch_unsup: 960
ratio_unsup: 5.0
ratio_mode: 'constant'

# training params
epoch: 1600
lr: 0.0001
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 300
    epoch: 120
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
