language: python
matrix:
  include:

    - name: "Python 3.7 on Linux"
      python: 3.7
      dist: xenial

    - name: "Python 3.6 on Linux"
      python: 3.6
      dist: xenial

    - name: "Python 3.5 on Linux"
      python: 3.5
      dist: xenial
      
install: pip3 install -r tests/travis_requirements.txt || pip3 install --user -r tests/travis_requirements.txt
script:
  - python3 --version || python --version
  - echo "import tests.travis_test" > test.py
  - coverage run --source models,examples test.py && coverage report

after_success:
  - codecov
  
