MODEL:
    TYPE: swin
    NAME: swin_t_64
    DROP_PATH_RATE: 0.2
    SWIN:
        EMBED_DIM: 96
        DEPTHS: [2, 2, 2, 2]
        NUM_HEADS: [3, 6, 12, 24]
        WINDOW_SIZE: 2
DATA:
    NUM_WORKERS: 0