Collections:
  - Name: NAS-FPN
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - NAS-FPN
        - ResNet
    Paper: https://arxiv.org/abs/1904.07392
    README: configs/nas_fpn/README.md

Models:
  - Name: retinanet_r50_fpn_crop640_50e_coco
    In Collection: NAS-FPN
    Config: configs/nas_fpn/retinanet_r50_fpn_crop640_50e_coco.py
    Metadata:
      Training Memory (GB): 12.9
      inference time (s/im): 0.04367
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.9
    Weights: http://download.openmmlab.com/mmdetection/v2.0/nas_fpn/retinanet_r50_fpn_crop640_50e_coco/retinanet_r50_fpn_crop640_50e_coco-9b953d76.pth

  - Name: retinanet_r50_nasfpn_crop640_50e_coco
    In Collection: NAS-FPN
    Config: configs/nas_fpn/retinanet_r50_nasfpn_crop640_50e_coco.py
    Metadata:
      Training Memory (GB): 13.2
      inference time (s/im): 0.04348
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.5
    Weights: http://download.openmmlab.com/mmdetection/v2.0/nas_fpn/retinanet_r50_nasfpn_crop640_50e_coco/retinanet_r50_nasfpn_crop640_50e_coco-0ad1f644.pth
