Collections:
  - Name: OCRNet
    Metadata:
      Training Data:
        - Cityscapes
        - Pascal VOC 2012 + Aug
        - ADE20K

Models:

  - Name: ocrnet_hr18s_512x1024_40k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 95.69
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 74.30
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18s_512x1024_40k_cityscapes/ocrnet_hr18s_512x1024_40k_cityscapes_20200601_033304-fa2436c2.pth
    Config: configs/ocrnet/ocrnet_hr18s_512x1024_40k_cityscapes.py



  - Name: ocrnet_hr18_512x1024_40k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 133.33
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.72
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18_512x1024_40k_cityscapes/ocrnet_hr18_512x1024_40k_cityscapes_20200601_033320-401c5bdd.pth
    Config: configs/ocrnet/ocrnet_hr18_512x1024_40k_cityscapes.py



  - Name: ocrnet_hr48_512x1024_40k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 236.97
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 80.58
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr48_512x1024_40k_cityscapes/ocrnet_hr48_512x1024_40k_cityscapes_20200601_033336-55b32491.pth
    Config: configs/ocrnet/ocrnet_hr48_512x1024_40k_cityscapes.py



  - Name: ocrnet_hr18s_512x1024_80k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 95.69
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.16
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18s_512x1024_80k_cityscapes/ocrnet_hr18s_512x1024_80k_cityscapes_20200601_222735-55979e63.pth
    Config: configs/ocrnet/ocrnet_hr18s_512x1024_80k_cityscapes.py



  - Name: ocrnet_hr18_512x1024_80k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 133.33
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.57
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18_512x1024_80k_cityscapes/ocrnet_hr18_512x1024_80k_cityscapes_20200614_230521-c2e1dd4a.pth
    Config: configs/ocrnet/ocrnet_hr18_512x1024_80k_cityscapes.py



  - Name: ocrnet_hr48_512x1024_80k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 236.97
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 80.70
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr48_512x1024_80k_cityscapes/ocrnet_hr48_512x1024_80k_cityscapes_20200601_222752-9076bcdf.pth
    Config: configs/ocrnet/ocrnet_hr48_512x1024_80k_cityscapes.py



  - Name: ocrnet_hr18s_512x1024_160k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 95.69
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.45
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18s_512x1024_160k_cityscapes/ocrnet_hr18s_512x1024_160k_cityscapes_20200602_191005-f4a7af28.pth
    Config: configs/ocrnet/ocrnet_hr18s_512x1024_160k_cityscapes.py



  - Name: ocrnet_hr18_512x1024_160k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 133.33
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.47
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18_512x1024_160k_cityscapes/ocrnet_hr18_512x1024_160k_cityscapes_20200602_191001-b9172d0c.pth
    Config: configs/ocrnet/ocrnet_hr18_512x1024_160k_cityscapes.py



  - Name: ocrnet_hr48_512x1024_160k_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 236.97
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 81.35
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr48_512x1024_160k_cityscapes/ocrnet_hr48_512x1024_160k_cityscapes_20200602_191037-dfbf1b0c.pth
    Config: configs/ocrnet/ocrnet_hr48_512x1024_160k_cityscapes.py



  - Name: ocrnet_r101-d8_512x1024_40k_b8_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: None
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU:
    Weights: https://github.com/open-mmlab/mmsegmentation/blob/master/configs/ocrnet/ocrnet_r101-d8_512x1024_40k_b8_cityscapes.py
    Config: configs/ocrnet/ocrnet_r101-d8_512x1024_40k_b8_cityscapes.py



  - Name: ocrnet_r101-d8_512x1024_40k_b16_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 113.64
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 3.02
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_r101-d8_512x1024_40k_b8_cityscapes/ocrnet_r101-d8_512x1024_40k_b8_cityscapes-02ac0f13.pth
    Config: configs/ocrnet/ocrnet_r101-d8_512x1024_40k_b16_cityscapes.py



  - Name: ocrnet_r101-d8_512x1024_80k_b16_cityscapes
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 113.64
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 3.02
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_r101-d8_512x1024_40k_b16_cityscapes/ocrnet_r101-d8_512x1024_40k_b16_cityscapes-db500f80.pth
    Config: configs/ocrnet/ocrnet_r101-d8_512x1024_80k_b16_cityscapes.py



  - Name: ocrnet_hr18s_512x512_80k_ade20k
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 34.51
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 35.06
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18s_512x512_80k_ade20k/ocrnet_hr18s_512x512_80k_ade20k_20200615_055600-e80b62af.pth
    Config: configs/ocrnet/ocrnet_hr18s_512x512_80k_ade20k.py



  - Name: ocrnet_hr18_512x512_80k_ade20k
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 52.83
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 37.79
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18_512x512_80k_ade20k/ocrnet_hr18_512x512_80k_ade20k_20200615_053157-d173d83b.pth
    Config: configs/ocrnet/ocrnet_hr18_512x512_80k_ade20k.py



  - Name: ocrnet_hr48_512x512_80k_ade20k
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 58.86
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 43.00
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr48_512x512_80k_ade20k/ocrnet_hr48_512x512_80k_ade20k_20200615_021518-d168c2d1.pth
    Config: configs/ocrnet/ocrnet_hr48_512x512_80k_ade20k.py



  - Name: ocrnet_hr18s_512x512_160k_ade20k
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 34.51
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 37.19
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18s_512x512_160k_ade20k/ocrnet_hr18s_512x512_160k_ade20k_20200615_184505-8e913058.pth
    Config: configs/ocrnet/ocrnet_hr18s_512x512_160k_ade20k.py



  - Name: ocrnet_hr18_512x512_160k_ade20k
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 52.83
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 39.32
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18_512x512_160k_ade20k/ocrnet_hr18_512x512_160k_ade20k_20200615_200940-d8fcd9d1.pth
    Config: configs/ocrnet/ocrnet_hr18_512x512_160k_ade20k.py



  - Name: ocrnet_hr48_512x512_160k_ade20k
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 58.86
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 43.25
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr48_512x512_160k_ade20k/ocrnet_hr48_512x512_160k_ade20k_20200615_184705-a073726d.pth
    Config: configs/ocrnet/ocrnet_hr48_512x512_160k_ade20k.py



  - Name: ocrnet_hr18s_512x512_20k_voc12aug
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 31.7
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 71.70
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18s_512x512_20k_voc12aug/ocrnet_hr18s_512x512_20k_voc12aug_20200617_233913-02b04fcb.pth
    Config: configs/ocrnet/ocrnet_hr18s_512x512_20k_voc12aug.py



  - Name: ocrnet_hr18_512x512_20k_voc12aug
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 50.23
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 74.75
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18_512x512_20k_voc12aug/ocrnet_hr18_512x512_20k_voc12aug_20200617_233932-8954cbb7.pth
    Config: configs/ocrnet/ocrnet_hr18_512x512_20k_voc12aug.py



  - Name: ocrnet_hr48_512x512_20k_voc12aug
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 56.09
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 77.72
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr48_512x512_20k_voc12aug/ocrnet_hr48_512x512_20k_voc12aug_20200617_233932-9e82080a.pth
    Config: configs/ocrnet/ocrnet_hr48_512x512_20k_voc12aug.py



  - Name: ocrnet_hr18s_512x512_40k_voc12aug
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 31.7
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 72.76
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18s_512x512_40k_voc12aug/ocrnet_hr18s_512x512_40k_voc12aug_20200614_002025-42b587ac.pth
    Config: configs/ocrnet/ocrnet_hr18s_512x512_40k_voc12aug.py



  - Name: ocrnet_hr18_512x512_40k_voc12aug
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 50.23
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 74.98
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18_512x512_40k_voc12aug/ocrnet_hr18_512x512_40k_voc12aug_20200614_015958-714302be.pth
    Config: configs/ocrnet/ocrnet_hr18_512x512_40k_voc12aug.py



  - Name: ocrnet_hr48_512x512_40k_voc12aug
    In Collection: OCRNet
    Metadata:
      inference time (ms/im):
        - value: 56.09
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 77.14
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr48_512x512_40k_voc12aug/ocrnet_hr48_512x512_40k_voc12aug_20200614_015958-255bc5ce.pth
    Config: configs/ocrnet/ocrnet_hr48_512x512_40k_voc12aug.py
